In [10]:
import pandas as pd
import datetime
import numpy as np
import matplotlib.pyplot as plt
import time
import datetime
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

In [11]:
EOCC_data = pd.read_csv('EOCC_New_data_with_zero_updated_columns.csv')

In [12]:
EOCC_data.head()

key  CAR NUMBER LOCATION  CONDITION CODE  is_new  RESPONSE CODE  \
0  83500A       83500        A               1       1              0   
1  83500B       83500        B               1       1              0   
2  83503A       83503        A               3       0              0   
3  83503B       83503        B               3       0              0   
4  83505A       83505        A               1       1              0   

   WHY MADE PART APPLIED DATE UPDATED PART REPAIR DATE  weeks_in_service  \
0         0         3/23/2018               11/15/2018                34   
1         0          6/6/2018               11/15/2018                24   
2         0        12/19/2014               11/15/2018                48   
3         0        10/20/2016               11/15/2018                 4   
4         0         6/22/2017               11/15/2018                21   

   ...   BOCT  CN   CPRS CSXT FXE  KCS  KCSM  NSS  ST    UP    
0  ...      0     3    0    3    0    0    0     4    0    15  
1  ...      0     3    0    3    0    0    0     4    0    15  
2  ...      0     6    0    6    0    0    0     5    0    23  
3  ...      0     6    0    6    0    0    0     5    0    23  
4  ...      0     9    3   12    0    1    0     2    0    28  

[5 rows x 117 columns]

In [13]:
data =EOCC_data.drop(['CAR NUMBER','key','LOCATION','RESPONSE CODE','WHY MADE','PART APPLIED DATE','UPDATED PART REPAIR DATE','UPDATED PART REPAIR DATE','BUILT DATE'],axis =1)

In [14]:
data['CAR_CLASS'] = pd.factorize(data.CAR_CLASS)[0]
data['EQUIP_FEAT_DESC'] = pd.factorize(data.EQUIP_FEAT_DESC)[0]
data['car_length'] = pd.factorize(data.car_length)[0]
data['car_tonnage'] = pd.factorize(data.car_tonnage)[0]
data['BUILDER_NAME'] = pd.factorize(data.BUILDER_NAME)[0]

In [15]:
df_new = pd.DataFrame(columns=['CAR_CLASS',
                               'EQUIP_FEAT_DESC',
                              'CONDITION CODE',
                              'BUILDER_NAME',
                              'EOCC_POCKET',
                              'weeks_in_service',
                              'Mileage_since_last _failure',
                               'car_age',
                               'Avg Mileage New Replace',
                               'Count of New Replacement',
                               'Avg Mileage Recond Replace',
                               'Count of Recond Replacement',
                               'Car life to date mileage',
                               'Loading_Count',
                               'TARGET'
                              ])

In [16]:
df_new['CAR_CLASS'] = data['CAR_CLASS']
df_new['EQUIP_FEAT_DESC'] = data['EQUIP_FEAT_DESC']
df_new['CONDITION CODE'] = data['CONDITION CODE']
df_new['BUILDER_NAME'] = data['BUILDER_NAME']
df_new['EOCC_POCKET'] = data['EOCC_POCKET']
df_new['weeks_in_service'] = data['weeks_in_service']
df_new['Mileage_since_last _failure'] = data['Mileage_since_last _failure']
df_new['car_age'] = data['car_age']
df_new['Avg Mileage New Replace'] = data['Avg Mileage New Replace']
df_new['Count of New Replacement'] = data['Count of New Replacement']
df_new['Avg Mileage Recond Replace'] = data['Avg Mileage Recond Replace']
df_new['Count of Recond Replacement'] = data['Count of Recond Replacement']
df_new['Car life to date mileage'] = data['Car life to date mileage']
df_new['Loading_Count'] = data['Loading_Count']
df_new['TARGET'] = data['TARGET']

In [17]:
y = df_new['TARGET']
x = df_new.drop(['TARGET'],axis =1)

In [18]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

x_train, x_test, y_train, y_test = train_test_split(x, y,random_state=0)

In [19]:
Hidden_layer_sizes = [50, 70, 90, 100, 130, 150, 200, 300]
Learning_rate_init = [0.01, 0.001, 0.0001]
Max_iter = [100, 200, 300, 500, 1000]
Learning_rate = ['constant', 'invscaling', 'adaptive']
epsilon = [1e-7, 1.5e-7, 1e-8, 1.5e-8, 1e-9]

In [ ]:
for h in Hidden_layer_sizes:
    for l in Learning_rate_init:
        for m in Max_iter:
            for lr in Learning_rate:
                for e in epsilon:
                    clf = MLPClassifier(solver='adam', hidden_layer_sizes = h, learning_rate_init = l, max_iter = m, learning_rate = lr, random_state=0,epsilon =e)
                    clf.fit(x_train,y_train) 
                    y_predict_test = clf.predict(x_test)
                    if confusion_matrix(y_test, y_predict_test)[1,1] > 40:
                        print(confusion_matrix(y_test, y_predict_test))
                        print('{0}-{1}-{2}-{3}-{4}'.format(h,l,m,lr,e))
                        a1 = confusion_matrix(y_test, y_predict_test)[0,0]/(confusion_matrix(y_test, y_predict_test)[0,0] + confusion_matrix(y_test, y_predict_test)[0,1])
                        b1 = confusion_matrix(y_test, y_predict_test)[1,1]/(confusion_matrix(y_test, y_predict_test)[1,1] + confusion_matrix(y_test, y_predict_test)[1,0])
                        print ('accuracy is {0}'.format((a1+b1)/2))

[[2140 3128]
 [  73  154]]
70-0.01-100-constant-1e-09
0.4062262718299165
0.6784140969162996
[[2140 3128]
 [  73  154]]
70-0.01-100-invscaling-1e-09
0.4062262718299165
0.6784140969162996
[[2140 3128]
 [  73  154]]
70-0.01-100-adaptive-1e-09
0.4062262718299165
0.6784140969162996
[[2140 3128]
 [  73  154]]
70-0.01-200-constant-1e-09
0.4062262718299165
0.6784140969162996
[[2140 3128]
 [  73  154]]
70-0.01-200-invscaling-1e-09
0.4062262718299165
0.6784140969162996
[[2140 3128]
 [  73  154]]
70-0.01-200-adaptive-1e-09
0.4062262718299165
0.6784140969162996
[[2140 3128]
 [  73  154]]
70-0.01-300-constant-1e-09
0.4062262718299165
0.6784140969162996
[[2140 3128]
 [  73  154]]
70-0.01-300-invscaling-1e-09
0.4062262718299165
0.6784140969162996
[[2140 3128]
 [  73  154]]
70-0.01-300-adaptive-1e-09
0.4062262718299165
0.6784140969162996
[[2140 3128]
 [  73  154]]
70-0.01-500-constant-1e-09
0.4062262718299165
0.6784140969162996
[[2140 3128]
 [  73  154]]
70-0.01-500-invscaling-1e-09
0.4062262718299165

In [ ]:

clf = MLPClassifier(solver='adam', hidden_layer_sizes = 90, learning_rate_init = 0.001, max_iter = 300, learning_rate = 'invscaling', random_state=0, alpha = 0.0001,epsilon =1e-8)

In [ ]:
clf.fit(x_train,y_train) 

In [ ]:
clf.score(x_test,y_test)

In [ ]:
clf.score(x_train,y_train)

In [ ]:
from sklearn.metrics import confusion_matrix
y_predict_test = clf.predict(x_test)
confusion_matrix(y_test, y_predict_test)